baseURL = 'https://rooty.github.io/'
languageCode = 'en-us'
title = 'Rooty protfolio'
theme = 'ananke'

[params]
  subtitle = 'The Best Widgets on Earth'
  [params.contact]
    email = 'blackrooty@gmail.com'
    phone = '+1 202-555-1212'
    
[markup]
  defaultMarkdownHandler = 'goldmark'
  